### PR TITLE
Allow "clip" to be specified in the mark/role config.

### PR DESCRIPTION
**Pull request by arvind**

### CODE REVIEW

**Comment by jheer** [comment]
A couple items to note:
1. There was a conditional logic bug in the `clip` property assignment (fixed by 97a693e).
2. Mark config objects currently are assumed to contain only valid mark encoding properties. As a result, any config `clip` property will also be written to every scenegraph item, not just applied to the mark definition. This occurs at [encode-util.js#L53](https://github.com/vega/vega-parser/blob/master/src/parsers/encode/encode-util.js#L53). One possible fix would be to update the "skip" logic to include a check for the `clip` property. The downside is that any additional mark-level (as opposed to item-level) properties we want to add in the future (`interactive`? `zindex`?) would also need to be added here as well. That said, I'm OK with the "quick fix" for now, **if** we're resigned to interleaving mark-level and item-level properties in the same config object. An annoying complication is that `clip` _is_ a valid item-level property for `group` marks...
3. We'll need to update the documentation in the vega/vega repo once changes go through here.

**Comment by jheer** [comment]
@arvind, any thoughts on issue 2 above? Given the ambiguity of mark-level vs. item-level application, I'm now tempted to punt on this PR. How necessary / useful is this feature for Vega-Lite, _etc_?

**Comment by arvind** [comment]
Sorry for the delay (and thanks for the bug fix!). I'm fine with having a more ambiguous mark configuration in favour of one that's more hierarchical. I suspect that only the most discerning of users would catch the ambiguity here, and it's something that I think can be explained via documentation if need be.

For a Vega-Lite use case, see [this scatterplot example](https://vega.github.io/vega-lite/docs/selection-translate.html). If the user explicitly sets scale domains that do not correspond to the data's `[min, max]`, points will overflow. Vega-Lite _does_ expose group-level clipping (`"config": {"cell": {"clip": true}}`) but that has the effect of clipping axes and legends as well.

**Comment by jheer** [comment]
OK, so the use case is to enable end-user configuration? My understanding is that in the context of selections we clip the marks to the data rectangle automatically. Should this be the default, regardless of selection status? (Of course, this is arguably tangential to the current issue.)

I'll take a look at "special casing" the `clip` property, but I'm still a bit hesitant...

**Comment by arvind** [comment]
Funnily enough, I was just thinking about whether `"clip": true` should be the default for all (non-group) marks Vega-Lite produces since you could have a bound-interval in one view manipulate another's that wouldn't have been clipped under our current scheme. 

So I'm ok with punting on this PR now.

**Pull request closed without merging**
