### PR TITLE
Coerce Date objects to numbers in selection tests.

### LINKED ISSUE #33: testPoint fails with Dates
`testPoint` uses a strict equality check which fails when comparing `Date` objects. In such cases, it should call `getTime` first.

### PR DESCRIPTION
**Pull request by arvind**
Fixes #33.

### CODE REVIEW

**Comment by jheer** [comment]
Is this PR ready to go? If so, assign to me. At quick glance it looks good, modulo some possible clean up for brevity.

**Comment by jheer** [comment]
I've gone ahead and merged. However, if possible it would be nice to move the date->number coercion to the logic that builds the selections in the first place "on write", rather than re-assigning values "on read". For example, might the current approach create type inconsistencies when exporting selection data? If this change was made, only the getter values would require date checking and coercion here in vega-parser.

**Comment by arvind** [comment]
Yeah, I thought about doing the type coercion "on write." But it becomes tricky to reliably predict when `Date` objects are created, and I didn't want to litter the signal update expressions with `isDate` ternary checks. The trickiest case occurs when an interval selection performs an `invertRange` over a `point` scale whose domain is `Date` objects. 

Happy to come back to this in the future, however!

**Comment by jheer** [comment]
OK, I'll go ahead and release as-is, but add some comments to the code about possibly revisiting this later.

**Pull request merged**
